server:
  port: 18082

spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
